export const pkgName = PKG_NAME;
export const pkgVersion = PKG_VERSION;

export const generatedSeparator = `<!-- Generated by ${pkgName}@v${pkgVersion}, please do not modify manually!! -->`;
export const generatedSeparatorRE = new RegExp(`<!-- .*?${pkgName}@v.*? -->`);
export const currentMajor = pkgVersion.split('.')[0];
