export const pkgName = process.env.PKG_NAME!;
export const pkgVersion = process.env.PKG_VERSION!;

export const generatedSeparator = `<!-- Generated by ${pkgName}@v${pkgVersion}, please do not modify manually!! -->`;
export const generatedSeparatorRE = new RegExp(`<!-- .*?${pkgName}@v.*? -->`);
